version: '3.9'

services:
  diploma-cache-metadata-postgres:
    image: postgres:latest
    container_name: diploma-cache-metadata-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"

  diploma-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: diploma-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - diploma-network

  diploma-kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: diploma-kafka
    depends_on:
      - diploma-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: diploma-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://diploma-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    networks:
      - diploma-network

  diploma-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: diploma-kafka-ui
    depends_on:
      - diploma-kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: diploma-kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: diploma-zookeeper:2181
    networks:
      - diploma-network

  diploma-debezium:
    image: debezium/connect:1.4
    container_name: diploma-debezium
    environment:
      BOOTSTRAP_SERVERS: diploma-kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - diploma-kafka
    ports:
      - 8083:8083
    networks:
      - diploma-network

  diploma-redis:
    image: redis:latest
    container_name: diploma-redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_USER=redis
      - REDIS_USER_PASSWORD=password
    ports:
      - "6379:6379"
    networks:
      - diploma-network

  #  etcd1:
  #    image: quay.io/coreos/etcd:v3.5.13
  #    container_name: etcd1
  #    environment:
  #      ETCD_NAME: etcd1
  #      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
  #      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
  #      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
  #      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
  #      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  #      ETCD_INITIAL_CLUSTER_STATE: new
  #      ETCD_INITIAL_CLUSTER_TOKEN: patroni-cluster
  #      ETCD_ENABLE_V2: "true"
  #    ports:
  #      - "2379:2379"
  #    networks:
  #      - diploma-network
  #
  #  etcd2:
  #    image: quay.io/coreos/etcd:v3.5.13
  #    container_name: etcd2
  #    environment:
  #      ETCD_NAME: etcd2
  #      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
  #      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
  #      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
  #      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
  #      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  #      ETCD_INITIAL_CLUSTER_STATE: new
  #      ETCD_INITIAL_CLUSTER_TOKEN: patroni-cluster
  #      ETCD_ENABLE_V2: "true"
  #    ports:
  #      - "2381:2379"
  #    networks:
  #      - diploma-network

  diploma-zookeeper-patroni-1:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: diploma-zookeeper-patroni-1
    hostname: diploma-zookeeper-patroni-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: diploma-zookeeper-patroni-1:2888:3888;diploma-zookeeper-patroni-2:2888:3888
    ports:
      - "2182:2181"
    volumes:
      - ./zookeeeper-script/zk-patroni-watcher.py:/zk-patroni-watcher.py
      - ./zookeeeper-script/entrypoint-zookeeper.sh:/entrypoint-zookeeper.sh
    command: >
      sh -c "
      cp /entrypoint-zookeeper.sh /tmp/entrypoint-zookeeper.sh &&
      chmod +x /tmp/entrypoint-zookeeper.sh &&
      /tmp/entrypoint-zookeeper.sh
      "
    networks:
      - diploma-network

  diploma-zookeeper-patroni-2:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: diploma-zookeeper-patroni-2
    hostname: diploma-zookeeper-patroni-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: diploma-zookeeper-patroni-1:2888:3888;diploma-zookeeper-patroni-2:2888:3888
    ports:
      - "2183:2181"
    networks:
      - diploma-network

  patroni1:
    build:
      context: ./patroni-master
      dockerfile: Dockerfile
    container_name: patroni1
    depends_on:
      - diploma-zookeeper-patroni-1
      - diploma-zookeeper-patroni-2
    environment:
      PATRONI_NAME: patroni1
      PATRONI_SCOPE: postgres-cluster
      PATRONI_NAMESPACE: /service/
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni1:8008
      PATRONI_ZOOKEEPER_HOSTS: "['diploma-zookeeper-patroni-1:2182', 'diploma-zookeeper-patroni-2:2183']"
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni1:5432
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator
      PATRONI_WAL_LEVEL: logical
    ports:
      - "5433:5432"
      - "8008:8008"
    networks:
      - diploma-network

  patroni2:
    build:
      context: ./patroni-master
      dockerfile: Dockerfile
    container_name: patroni2
    depends_on:
      - diploma-zookeeper-patroni-1
      - diploma-zookeeper-patroni-2
    environment:
      PATRONI_NAME: patroni2
      PATRONI_SCOPE: postgres-cluster
      PATRONI_NAMESPACE: /service/
      PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni2:8008
      PATRONI_ZOOKEEPER_HOSTS: "['diploma-zookeeper-patroni-1:2182', 'diploma-zookeeper-patroni-2:2183']"
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni2:5432
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: replicator
      PATRONI_WAL_LEVEL: logical
    ports:
      - "5434:5432"
      - "8009:8008"
    networks:
      - diploma-network

  diploma-experiment-postgres:
    image: postgres:latest
    container_name: diploma-experiment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"


networks:
  diploma-network:
    driver: bridge